In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
df = pd.read_csv("../data/weather_data.csv")

In [65]:
df.head()

   YEAR  MO  DY  HR   T2M   RH2M     PS
0  2023   1   1   0  7.60  66.63  99.51
1  2023   1   1   1  7.01  68.41  99.49
2  2023   1   1   2  6.95  68.69  99.49
3  2023   1   1   3  6.31  70.77  99.46
4  2023   1   1   4  6.12  71.02  99.45

In [66]:
df[(df['T2M'] == -999)].shape

(72, 7)

In [67]:
df[(df['RH2M'] == -999)].shape

(72, 7)

In [68]:
df[(df['PS'] == -999)].shape

(72, 7)

In [69]:
df[(df['T2M'] == -999) |
   (df['RH2M'] == -999) |
   (df['PS'] == -999)].shape

(72, 7)

In [70]:
df[(df['T2M'] == -999) & 
   (df['RH2M'] == -999) & 
   (df['PS'] == -999)].shape

(72, 7)

In [71]:
df[['T2M', 'RH2M', 'PS']] = df[['T2M', 'RH2M', 'PS']].replace(-999, np.nan)

In [72]:
df.isnull().sum()

YEAR     0
MO       0
DY       0
HR       0
T2M     72
RH2M    72
PS      72
dtype: int64

In [73]:
df.dropna(subset=['T2M', 'RH2M', 'PS'], inplace=True)

In [74]:
df.shape

(31848, 7)

In [75]:
df['datetime'] = pd.to_datetime(
    df[['YEAR', 'MO', 'DY', 'HR']]
    .rename(columns={
        'YEAR': 'year',
        'MO': 'month',
        'DY': 'day',
        'HR': 'hour'
    })
)

In [76]:
df.head()

   YEAR  MO  DY  HR   T2M   RH2M     PS            datetime
0  2023   1   1   0  7.60  66.63  99.51 2023-01-01 00:00:00
1  2023   1   1   1  7.01  68.41  99.49 2023-01-01 01:00:00
2  2023   1   1   2  6.95  68.69  99.49 2023-01-01 02:00:00
3  2023   1   1   3  6.31  70.77  99.46 2023-01-01 03:00:00
4  2023   1   1   4  6.12  71.02  99.45 2023-01-01 04:00:00

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31848 entries, 0 to 31847
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   YEAR      31848 non-null  int64
 1   MO        31848 non-null  int64
 2   DY        31848 non-null  int64
 3   HR        31848 non-null  int64
 4   T2M       31848 non-null  float64
 5   RH2M      31848 non-null  float64
 6   PS        31848 non-null  float64
 7   datetime  31848 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(4)
memory usage: 2.2 MB

In [78]:
df[['YEAR', 'MO', 'DY', 'HR', 'datetime']]

       YEAR  MO  DY  HR            datetime
0      2023   1   1   0 2023-01-01 00:00:00
1      2023   1   1   1 2023-01-01 01:00:00
2      2023   1   1   2 2023-01-01 02:00:00
3      2023   1   1   3 2023-01-01 03:00:00
4      2023   1   1   4 2023-01-01 04:00:00
...     ...  ..  ..  ..                 ...
31843  2026   8  19  19 2026-08-19 19:00:00
31844  2026   8  19  20 2026-08-19 20:00:00
31845  2026   8  19  21 2026-08-19 21:00:00
31846  2026   8  19  22 2026-08-19 22:00:00
31847  2026   8  19  23 2026-08-19 23:00:00

[31848 rows x 5 columns]

In [79]:
df.drop(columns=['YEAR', 'MO', 'DY', 'HR'], inplace=True)

In [80]:
df.head()

    T2M   RH2M     PS            datetime
0  7.60  66.63  99.51 2023-01-01 00:00:00
1  7.01  68.41  99.49 2023-01-01 01:00:00
2  6.95  68.69  99.49 2023-01-01 02:00:00
3  6.31  70.77  99.46 2023-01-01 03:00:00
4  6.12  71.02  99.45 2023-01-01 04:00:00

In [81]:
df['PS'] = df['PS']*10

In [82]:
df['datetime'] = pd.to_datetime(df['datetime'])

In [83]:
df['datetime'].dtype

dtype('<M8[ns]')

In [86]:
df.to_csv("../data/weather_cleaned.csv", index=False)